networks:
  redis_dev_network:
    driver: bridge
    name: redis-dev-network

volumes:
  redis_dev_data:
    driver: local
    name: redis-dev-data-volume

services:
  redis:
    image: redis:8.4
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
    networks:
      - redis_dev_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
